package com.niuyunzhipin.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.niuyun.hire.ui.bean.AllTagBean;
import com.niuyun.hire.ui.bean.DataBean;

import com.niuyunzhipin.greendao.AllTagBeanDao;
import com.niuyunzhipin.greendao.DataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allTagBeanDaoConfig;
    private final DaoConfig dataBeanDaoConfig;

    private final AllTagBeanDao allTagBeanDao;
    private final DataBeanDao dataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allTagBeanDaoConfig = daoConfigMap.get(AllTagBeanDao.class).clone();
        allTagBeanDaoConfig.initIdentityScope(type);

        dataBeanDaoConfig = daoConfigMap.get(DataBeanDao.class).clone();
        dataBeanDaoConfig.initIdentityScope(type);

        allTagBeanDao = new AllTagBeanDao(allTagBeanDaoConfig, this);
        dataBeanDao = new DataBeanDao(dataBeanDaoConfig, this);

        registerDao(AllTagBean.class, allTagBeanDao);
        registerDao(DataBean.class, dataBeanDao);
    }
    
    public void clear() {
        allTagBeanDaoConfig.clearIdentityScope();
        dataBeanDaoConfig.clearIdentityScope();
    }

    public AllTagBeanDao getAllTagBeanDao() {
        return allTagBeanDao;
    }

    public DataBeanDao getDataBeanDao() {
        return dataBeanDao;
    }

}
