package com.niuyunzhipin.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.niuyun.hire.ui.bean.AllTagBean;
import com.niuyun.hire.ui.bean.City;
import com.niuyun.hire.ui.bean.DataBean;
import com.niuyun.hire.ui.bean.SearchHistoryBean;

import com.niuyunzhipin.greendao.AllTagBeanDao;
import com.niuyunzhipin.greendao.CityDao;
import com.niuyunzhipin.greendao.DataBeanDao;
import com.niuyunzhipin.greendao.SearchHistoryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allTagBeanDaoConfig;
    private final DaoConfig cityDaoConfig;
    private final DaoConfig dataBeanDaoConfig;
    private final DaoConfig searchHistoryBeanDaoConfig;

    private final AllTagBeanDao allTagBeanDao;
    private final CityDao cityDao;
    private final DataBeanDao dataBeanDao;
    private final SearchHistoryBeanDao searchHistoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allTagBeanDaoConfig = daoConfigMap.get(AllTagBeanDao.class).clone();
        allTagBeanDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        dataBeanDaoConfig = daoConfigMap.get(DataBeanDao.class).clone();
        dataBeanDaoConfig.initIdentityScope(type);

        searchHistoryBeanDaoConfig = daoConfigMap.get(SearchHistoryBeanDao.class).clone();
        searchHistoryBeanDaoConfig.initIdentityScope(type);

        allTagBeanDao = new AllTagBeanDao(allTagBeanDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);
        dataBeanDao = new DataBeanDao(dataBeanDaoConfig, this);
        searchHistoryBeanDao = new SearchHistoryBeanDao(searchHistoryBeanDaoConfig, this);

        registerDao(AllTagBean.class, allTagBeanDao);
        registerDao(City.class, cityDao);
        registerDao(DataBean.class, dataBeanDao);
        registerDao(SearchHistoryBean.class, searchHistoryBeanDao);
    }
    
    public void clear() {
        allTagBeanDaoConfig.clearIdentityScope();
        cityDaoConfig.clearIdentityScope();
        dataBeanDaoConfig.clearIdentityScope();
        searchHistoryBeanDaoConfig.clearIdentityScope();
    }

    public AllTagBeanDao getAllTagBeanDao() {
        return allTagBeanDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public DataBeanDao getDataBeanDao() {
        return dataBeanDao;
    }

    public SearchHistoryBeanDao getSearchHistoryBeanDao() {
        return searchHistoryBeanDao;
    }

}
